spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: ResuFit

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# JWT 공통 설정
# secret은 env.local / env.prod에서 주입
jwt:
  secret: ${JWT_SECRET:TBPDhjuISK47hECb28vUpImQQsRPPwP68RsJmt/8B/o=}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}      # 30분
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000} # 14일

# OAuth 공통 endpoint
oauth:
  google:
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
  kakao:
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3307/resufit
    username: root
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

logging:
  level:
    com.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI}

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:resume}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:resufit}
    password: ${MYSQL_PASSWORD:resufit1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # https 테스트 중에만 update 운영 시 validate
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

logging:
  level:
    com.backend: INFO
    org.hibernate.SQL: INFO

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI}