spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: ResuFit

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3307/resume?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

logging:
  level:
    com.resufit: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-resume}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:-resufit}
    password: ${MYSQL_PASSWORD:-resufit1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

logging:
  level:
    com.resufit: INFO